[build]
  command = "pip install -r requirements.txt && python app.py"
  publish = "/opt/build/repo"

[build.environment]
  FLASK_ENV = "production"

[redirects]
  [[redirects]]
    from = "/old-path"
    to = "/new-path"
    status = 301
